---
title: "Yahoo! Finance Data Test 2"
author: "Christian Maruhn"
date: "2024-05-05"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
#########################################################################################
# Method 2
#########################################################################################
# Required packages
library(BatchGetSymbols)
library(ggplot2)
library(dplyr)

# Download the share prices for Berkshire Hathaway (BRK-B) 
# from = '2010-01-01', to = "2020-01-01"
BRK <- BatchGetSymbols(tickers = 'BRK-B', 
                first.date = '2010-01-01',
                last.date = '2020-01-01', 
                freq.data = 'daily',
                cache.folder = file.path(tempdir(), 
                                         'BRK-B') ) 


# Transforming the data into a data frame
dat <- data.frame(BRK$df.tickers)
colnames(dat) <- names(BRK$df.tickers)

# An excerpt of the data
head(dat)
```

```{r setup, include=FALSE}
# Let's focus on the Adjusted close price 
data1 <- dat[,"price.adjusted"]

hist(data1, breaks = 50, xlab = "price.adjusted", probability = TRUE, 
     cex.axis = 1.5, cex.lab = 1.5)
box()
```

```{r setup, include=FALSE}
summary(data1)
```

```{r setup, include=FALSE}
# Time series plot
ts <- data.frame(
  day = dat$ref.date,
  Price = dat[,"price.adjusted"]
)

p <- ggplot(ts, aes(x=day, y=Price)) +
  geom_line()  + theme(text = element_text(size = 20), axis.text.x = element_text(size = 10))
p+scale_x_date(date_labels = "%Y %b %d")
```

```{r setup, include=FALSE}
# Calculating the 1-day log returns

# Sample size
n <- length(data1)

# Log returns
LR <- log( data1[-1]/ data1[-n])

hist(LR, breaks = 50, xlab = "Log-Returns", probability = TRUE, 
     cex.axis = 1.5, cex.lab = 1.5, main = "1-Day Log-returns")
box()  
```
