---
title: "Yahoo! Finance Data Test 1"
author: "Christian Maruhn"
date: "2024-04-20"
output: html_document
---

```{r setup, include=FALSE}
rm(list=ls())
#########################################################################################
# Method 1
#########################################################################################
# Required packages
library(tidyquant)
library(ggplot2)
library(dplyr)

# Download the share prices for Berkshire Hathaway (BRK-B) 
# from = '2010-01-01', to = "2020-01-01"
getSymbols("BRK-B", from = '2010-01-01',
           to = "2023-04-01",warnings = FALSE,
           auto.assign = TRUE)
```

```{r setup, include=FALSE}
# An excerpt of the data
head(`BRK-B`)
```

```{r setup, include=FALSE}
# Transforming the data into a data frame
dat <- data.frame(`BRK-B`)
colnames(dat) <- names(`BRK-B`)

# Let's focus on the Adjusted close price 
data1 <- dat[,"BRK-B.Adjusted"]

hist(data1, breaks = 50, xlab = "BRK-B.Adjusted", probability = TRUE, 
     cex.axis = 1.5, cex.lab = 1.5)
box()
```

```{r setup, include=FALSE}
summary(data1)

```

```{r setup, include=FALSE}
# Time series plot
ts <- data.frame(
  day = as.Date(rownames(dat)),
  Price = dat[,"BRK-B.Adjusted"]
)

p <- ggplot(ts, aes(x=day, y=Price)) +
  geom_line()  + theme(text = element_text(size = 20), axis.text.x = element_text(size = 10))
p+scale_x_date(date_labels = "%Y %b %d")
```

```{r setup, include=FALSE}
# Calculating the 1-day log returns

# Sample size
n <- length(data1)

# Log returns
LR <- log( data1[-1]/ data1[-n])

hist(LR, breaks = 50, xlab = "Log-Returns", probability = TRUE, 
     cex.axis = 1.5, cex.lab = 1.5, main = "1-Day Log-returns")
box() 
```
